name: CI

on:
  push:

jobs:
  test:

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [macOS-latest, windows-latest, ubuntu-latest, macOS-11.0]
        poetry-version: [1.0.5]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      
      - name: Poetry install
        run: poetry install

      # - name: Build Ubuntu packages
      #   if: contains(matrix.os, 'ubuntu')
      #   run: |
      #     poetry add secretstorage
      #     sudo apt-get install libdbus-1-dev libdbus-glib-1-dev
      #     poetry add dbus-python

      - name: Poetry test
        env:
          CREDENTIALS_FILE_CONTENTS : ${{ secrets.AWS_CREDENTIALS_FILE_CONTENTS }}
        working-directory: ./tests
        run: poetry run pytest --cov ../mentaws tests/ --cov-report term-missing -vv

      - name: Update Test Coverage
        if: github.ref == 'refs/heads/release'  # only on the feature branch do we publish code coverage stats
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }} 
        working-directory: ./tests
        run: poetry run coveralls

